const mongoose=require('mongoose')

const issueRegisterSchema=mongoose.Schema({
    SerialNo:{
        type:Number,
        required:true
    },
    ProductCode:{
        type:String,
        required:true
    },
    ProductName:{
        type:String,
        required:true
    },
    GenericName:{
        type:String,
        required:true
    },
    DateOfIssue:{
        type:Date,
        required:true
    },
    BatchNo:{
        type:Number,
        required:true
    },
    ProductName:{
        type:String,
        required:true
    },
    GenericName:{
        type:String,
        required:true
    },
    SerialNo:{
        type:String,
        required:true
    },
    ProductCode:{
        type:String,
        required:true
    },
    ProductName:{
        type:String,
        required:true
    },
    GenericName:{
        type:String,
        required:true
    },

})